<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'هل انت متاكد من حذف هذا العنصر',
    'Create' => 'اضافة',
    'Create Feeds' => ' إضافة Rss',
	'Create Res' => ' إضافة موقع',
	'Create Topics' => ' إضافة فئة',
	'Topics' => 'الفئات',
	
	'Res' => ' المواقع',
	'Trends' => 'مواضيع نشطة',
	'Create Trends' => 'موضوع جديد',
	'Slug' => ' #هاشتاج',
	'From Date' => 'إبتداء من ',
	'Must Contain' => 'يجب ان يحتوي على الكلمات ',
	'Contain' => 'يحتوي على احدى الكلمات',
	'Not Contain' => 'يجب ان لا يحتوي على',
	'Key Words' => 'كلمات دلالية',
	'Description' => 'وصف',
	
    'Delete' => 'حذف',
    'Reset' => 'مسح',
	'Save' => 'حفظ',
    'ID' => '#',
	'Cat' => 'الفئة',
	'Type' => 'نوعية الأخبار',
	'Res ID' => 'رقم المصدر',
	'Search' => 'بحث',
    'Text' => 'وصف',
    'Feeds' => 'روابط Rss',
    'Update' => 'تعديل',
    'Update Res {nameAttribute}:' => 'تعديل المصدر{nameAttribute}:',
	'Update Res: {nameAttribute}' => 'تعديل موقع: {nameAttribute}',
    'Update Topics: {nameAttribute}' => 'تعديل فئة: {nameAttribute}',
    'Update Feeds: {nameAttribute}' => 'تعديل : {nameAttribute}',
    'Add Rss: {nameAttribute}' => ' إضافة rss : {nameAttribute}',
    'Feedurl' => 'رابط',
	'add rss' => '  إضافة rss ',
	'fetch logo' => ' جلب الشعار ',
	'Add New' => 'إضافةجديد',
	
   
	'Interval' => 'تعديل كل(دقيقة)',
	'Logo' =>'شعار الموقع',
	'Trend' =>'التوجه',
	
	 'Active' => 'الحالة',
	 'Name' => 'الإسم',
	 'R Name' => 'إسم الموقع',
	 'account disabled' => 'تم تعطيل الحساب بنجاح',
	 'account eabled' => 'تم تنشيط الحساب بنجاح',
	 'Create Twitter User' => 'إضافة مغرد جديد',
	 'Twitter Users' => 'ادارة المغردون',
	 
	  
];
